### ISSUE TITLE
Enemies only hit the player once, then stop attacking you

### ISSUE THREAD

**Issue by DanielDestefanis** [AIESydProgYr12021/aie_cpd-BenMate#11]
If you get hit by an enemy, you lose 1 health, but afterwards you don't lose health from them anymore.
To replicate this, if you stand still and let an enemy attack you, they do, but then they just run on the spot and don't harm you again until you move.

**Comment by BenMate** [comment]
Enemies now have a OnColiderStay and OnColiderExit functions so you will take damage over time when they are next to you.
