### ISSUE TITLE
Slow Run

### ISSUE THREAD

**Issue by Oraxien40** [AIESydProgYr12021/aie_cpd-BenMate#13]
DESCRIPTION: On Android, the player is slower than the web version.
PRIORITY: A
PLATFORMS: Android
REPRODUCTION: run away from the enemy's on both platforms and compare their speeds

**Comment by BenMate** [comment]
potentially fixed on build:
8282884

potential fix: ive moved the joystick in more so you can fully move it across for full movement

**Comment by Oraxien40** [comment]
just played build 0.5. 
great job on the fix works great except it has uncovered a new issue.
Now when you play the game. whenever your run to the left you move at a slower pace than if you move right or forward.

**Comment by Oraxien40** [comment]
just realize that the android walk issue already covers this

**Comment by BenMate** [comment]
fixed: https://github.com/AIESydProgYr12021/aie_cpd-BenMate/issues/19
