### ISSUE TITLE
[BUG] Enemies phase through geometry (on all platforms)

### ISSUE THREAD

**Issue by DanielDestefanis** [AIESydProgYr12021/aie_cpd-BenMate#14]
Description: Enemies phase through all geometry in the desert map. This mainly includes the gas station, wind mill, and sign. 
Priority: C
Platforms: All platforms
Build: Build from 07/09/2021
Reproduction: Lead enemies to the gas station, and get them to phase through. You can immediately notice this bug when you spawn in at the start of the level.

**Comment by BenMate** [comment]
fixed on commit:
2b5ff7e 

Removed: nevMeshing around certain objects preventing the enemy from walking inside the petrol station
Added: they now path around the petrol station

Note: further testing might be needed incase there are more safe spots or some objects / geomatry doesnt work as now intended.

**Comment by DanielDestefanis** [comment]
The petrol station area is fixed, enemies are now correctly pathing their way around. 
The enemies are still phasing through the windmill and the big sign however. 
Note: This isnt so much of an issue with the smaller enemies, as it kinda makes more sense. However, its more of a problem with the big zombies.

**Comment by BenMate** [comment]
removed some of the navMesh around the sign and the poles hopefully now they dont walk through them.

**Comment by DanielDestefanis** [comment]
Yep all fixed!
