### ISSUE TITLE
[BUG] Pause menu quit button freezes the game (Web version)

### ISSUE THREAD

**Issue by DanielDestefanis** [AIESydProgYr12021/aie_cpd-BenMate#15]
Description: The quit button in the pause menu freezes the game. 
Priority: B
Platforms: Web 
Build & Environment: Build from 07/09/2021 (build 2) 
Reproduction: Pause the game, and press the quit button 

Would advise removing the quit button from this menu, leaving just the Menu button.

**Comment by BenMate** [comment]
fix: removed the quit botton from the pause menu

**Comment by DanielDestefanis** [comment]
Yep fixed!
