### ISSUE TITLE
Android controls

### ISSUE THREAD

**Issue by Oraxien40** [AIESydProgYr12021/aie_cpd-BenMate#16]
Description: 
< the android controls don't allow for left right and backwards movement.>
Priority: < A >
Platforms: <Android>
Build & Environment: <Build7/09/2021 >
Reproduction: 
< the android UI controls >

**Comment by BenMate** [comment]
fixed on commit: 
2b5ff7e 

Added: Added a second joystick for android
Added: ability to shoot with second joystick

**Comment by Oraxien40** [comment]
The second joystick vastly improves the game.
I have no further issues with the controls
