### ISSUE TITLE
[BUG] Collision bug on rocks

### ISSUE THREAD

**Issue by DanielDestefanis** [AIESydProgYr12021/aie_cpd-BenMate#17]
Description: The rocks in the top right of the map have no collision, compared to the rest of the rocks in the map. 
Priority: D
Platforms: All platforms 
Build & Environment: Build from 07/09/2021 (Build 2)
Reproduction: Run to the top right of the map, and run through the rocks.

**Comment by BenMate** [comment]
fixed on build:
6b28be3

Added: added an invisible wall to the edges of the map only the player colides with.
added: a box collider on the rocks.

**Comment by DanielDestefanis** [comment]
Yep working as intended
