### ISSUE TITLE
[BUG] Android pause

### ISSUE THREAD

**Issue by Oraxien40** [AIESydProgYr12021/aie_cpd-BenMate#18]
Description: 
there is no pause button
Priority: <A>
Platforms: <Android>
Build & Environment: <Build 7/09/2021>

**Comment by BenMate** [comment]
fixed in commit:
2b5ff7e 

Added: a pause button only on android on the top left of the screen.

**Comment by Oraxien40** [comment]
bugfixed can now pause the game
