### ISSUE TITLE
[BUG] Android walk

### ISSUE THREAD

**Issue by Oraxien40** [AIESydProgYr12021/aie_cpd-BenMate#19]
Description: 
when you walk left or towards the camera you sometimes slow down
Priority: B
Platforms: Android
Build & Environment: build7/09/2021
Reproduction: 
Change the direction you are walking.

**Comment by BenMate** [comment]
fixed on build: 
8282884

fixed: moved joystick closer to the middle of the screen this allows you to move the joystick more left to get the full movement.
