### ISSUE TITLE
[BUG] Health meter can be manipulated by player

### ISSUE THREAD

**Issue by DanielDestefanis** [AIESydProgYr12021/aie_cpd-BenMate#20]
Description: You can click and drag the health meter on Web and Windows. You can use the touch pad to do the same thing on Android. 
Priority: A
Platforms: All 
Build & Environment: Build from 07/09/2021 (build 2)
Reproduction: Click and drag, or use touch pad over the health bar area to manipulate.

**Comment by BenMate** [comment]
fixed on build:
6b28be3

removed: slider is no longer  Interactable.

**Comment by DanielDestefanis** [comment]
Yep can no longer interact with the health bar, fixed!
