### ISSUE TITLE
Sometimes you don't fire where you are aiming

### ISSUE THREAD

**Issue by DanielDestefanis** [AIESydProgYr12021/aie_cpd-BenMate#9]
There's times where you aim at an enemy and it doesnt fire where you're aiming

**Comment by BenMate** [comment]
@DanielDestefanis 
Can you close the issue after verifying - I've added a label "ToReview" and assigned the ticket back to you.

**Comment by DanielDestefanis** [comment]
Aiming bug fixed, working as intended
